version: "2.3"
services:
  mysql1:
    image: mysql:8.0
    container_name: dbpack-mysql1
    networks:
      - local
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
    - ./data1:/var/lib/mysql:z
    - ./mysqld1/:/var/run/mysqld:z
    - ./scripts/:/docker-entrypoint-initdb.d/:rw
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  mysql2:
    image: mysql:8.0
    container_name: dbpack-mysql2
    networks:
      - local
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./data2:/var/lib/mysql:z
      - ./mysqld2/:/var/run/mysqld:z
      - ./scripts/:/docker-entrypoint-initdb.d/:rw
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
  dbpack:
    image: dbpack:latest
    container_name: dbpack
    command: sh -c "sleep 60 && ./dbpack start -c config.yaml"
    networks:
      - local
    ports:
    - "13306:13306"
    volumes:
    - ./conf/config_rws.yaml:/app/config.yaml
    depends_on:
      - mysql1
      - mysql2
networks:
  local:
    name: dbpack