listeners:
  - protocol_type: mysql
    socket_address:
      address: 0.0.0.0
      port: 13306
    config:
      users:
        dksl: "123456"
      server_version: "8.0.27"
    executor: redirect

executors:
  - name: redirect
    mode: sdb
    config:
      data_source_ref: employees

data_source_cluster:
  - name: employees
    capacity: 10
    max_capacity: 20
    idle_timeout: 60s
    dsn: root:123456@tcp(dbpack-mysql:3306)/employees?timeout=60s&readTimeout=60s&writeTimeout=60s&parseTime=true&loc=Local&charset=utf8mb4,utf8
    ping_interval: 20s
    ping_times_for_change_status: 3
    filters:
      - metricFilter
      - mysqlDTFilter

filters:
  - name: mysqlDTFilter
    kind: MysqlDistributedTransaction
    conf:
      appid: svc
      lock_retry_interval: 50ms
      lock_retry_times: 30
  - name: metricFilter
    kind: ConnectionMetricFilter

distributed_transaction:
  appid: svc
  retry_dead_threshold: 130000
  rollback_retry_timeout_unlock_enable: true
  etcd_config:
    endpoints:
      - etcd:2379

exporter_port: 9999